
enable_inventory_module=true
enable_staff_module=true
enable_course_module=true
enable_trial_module=true
enable_proband_module=true
enable_input_field_module=true
enable_user_module=true
enable_mass_mail_module=true

public_file_signup_url={0}/signup/file/{1}
trial_signup_url={0}/signup/proband?trial={1}